@baseUrl = http://localhost:8000

### Get list of events
GET {{baseUrl}}/api/events

### Get a specific event by ID
GET {{baseUrl}}/api/events/1

### Create a new event
POST {{baseUrl}}/api/events
Content-Type: application/json

{
  "name": "New Event",
  "dateTime": "2021-12-31T23:59:00",
  "description": "New Year's Eve Celebration"
}

### Update an existing event
PUT {{baseUrl}}/api/events/1
Content-Type: application/json

{
  "name": "Updated Event Name",
  "dateTime": "2021-12-31T23:59:00",
  "description": "Updated Description"
}

### Delete an event
DELETE {{baseUrl}}/api/events/1
